import type { MvpOrder } from "./mvp-types";
import { makePiece } from "./fixture-builders";
import { makeSegment } from "./mvp-selectors";

export const qualityOrders: MvpOrder[] = [
  // 7. Repair Order skipping Cutting directly to Production
  {
    id: "REPAIR-2026-0003",
    type: "REPAIR",
    customer: "يوسف الشريف",
    phone: "0531187042",
    address: "حي النزهة، مكة",
    salesperson: "ريم خالد",
    created: "٠٩ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-09",
    delivery: "١٨ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-18",
    status: "قيد التصنيع",
    cancelled: 0,
    warehouse: 0,
    repairNote:
      "فك الأرضية القديمة وإعادة تثبيت أرضية جديدة مع شد الجلد العلوي",
    items: [
      makePiece("i-r3-1", 0, "إصلاح نعل وشد جلد", {
        sole: "R.D ربل مقوى",
        unitPrice: "180",
        rowTotal: "180",
        currentLocation: "في الإنتاج",
        deptStatus: "مرتجعة للتصحيح",
      }),
      makePiece("i-r3-2", 1, "إصلاح نعل وشد جلد", {
        sole: "R.D ربل مقوى",
        unitPrice: "180",
        rowTotal: "180",
        currentLocation: "في الجودة",
        deptStatus: "جاهزة للفحص",
      }),
    ],
    segments: [
      makeSegment(
        "s-r3a",
        "i-r3-1",
        "الإنتاج والإصلاح",
        1,
        "معادة من الجودة",
        "عدم ثبات الغراء على الكعب الأيمن · إعادة اللصق والكبس الحراري",
        "الجودة والتغليف",
        1,
      ),
      makeSegment(
        "s-r3b",
        "i-r3-2",
        "الجودة والتغليف",
        1,
        "إعادة فحص",
        "تم تصحيح قطعة وإعادتها للفحص",
        "الإنتاج والإصلاح",
        2,
      ),
    ],
    corrections: [
      {
        id: "qc-r3",
        itemId: "i-r3-1",
        segmentId: "s-r3a",
        quantity: 1,
        responsible: "الإنتاج والإصلاح",
        reason: "عدم ثبات الغراء على الكعب الأيمن",
        instructions: "تنظيف القاعدة وإعادة الكبس الحراري وضغط ٤ ساعات",
        cycle: 1,
        date: "١٠ سبتمبر · ٠٩:٣٠",
        actor: "منى سعيد",
        resolved: false,
      },
    ],
  },
  // 8. Corrected Quantity awaiting Reinspection
  {
    id: "EXTERNAL-2026-0006",
    type: "EXTERNAL",
    customer: "دار الأصالة",
    phone: "0559123400",
    address: "حي الشرفية، جدة",
    salesperson: "ليان سعد",
    created: "٠٧ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-07",
    delivery: "٢٢ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-22",
    status: "قيد التصنيع",
    cancelled: 0,
    warehouse: 0,
    items: [
      makePiece("i-06-1", 0, "OS-194", {
        decoration: "تطريز يدوي فاخر",
        currentLocation: "في الجودة",
        deptStatus: "جاهزة للفحص",
      }),
      makePiece("i-06-2", 1, "OS-194", {
        decoration: "تطريز يدوي فاخر",
        currentLocation: "في الجودة",
        deptStatus: "جاري الفحص",
        responsibleWorker: "منى سعيد",
      }),
    ],
    segments: [
      makeSegment(
        "s-06b",
        "i-06-1",
        "الجودة والتغليف",
        2,
        "إعادة فحص",
        "اكتمل تصحيح التطريز في العمليات الخاصة وعادت الدفعة للفحص النهائي",
        "العمليات الخاصة",
        2,
      ),
    ],
    corrections: [
      {
        id: "qc-06",
        itemId: "i-06-1",
        segmentId: "s-06a",
        quantity: 2,
        responsible: "العمليات الخاصة",
        reason: "انحراف خيط التطريز عن المسار المعتمد",
        instructions: "إعادة ضبط التطريز وتثبيت الأطراف بخيط حريري مطابق",
        cycle: 1,
        date: "٠٩ سبتمبر · ١٥:٠٠",
        actor: "منى سعيد",
        resolved: true,
      },
    ],
  },
  // 9. Partially Cancelled Order (Original 5, Cancelled 1, Active 4, Received 3)
  {
    id: "SHOP-2026-0001",
    type: "SHOP",
    customer: "سعود المنصور",
    phone: "0501112233",
    address: "حي الروضة، جدة",
    salesperson: "ريم خالد",
    created: "٠٨ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-08",
    delivery: "٢٠ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-20",
    status: "ملغي جزئياً",
    cancelled: 1,
    warehouse: 3,
    items: [
      makePiece("i-01-1", 0, "OS-214", {
        size: "٤٢",
        unitPrice: "420",
        rowTotal: "420",
        currentLocation: "في المستودع",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-01-2", 1, "OS-214", {
        size: "٤٢",
        unitPrice: "420",
        rowTotal: "420",
        currentLocation: "في المستودع",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-01-3", 2, "OS-214", {
        size: "٤٢",
        unitPrice: "420",
        rowTotal: "420",
        currentLocation: "في المستودع",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-01-4", 3, "OS-214", {
        size: "٤٢",
        unitPrice: "420",
        rowTotal: "420",
        currentLocation: "في الجودة",
        deptStatus: "جاهزة للفحص",
      }),
      makePiece("i-01-5", 4, "OS-214", {
        size: "٤٢",
        unitPrice: "420",
        rowTotal: "420",
        isDeleted: true,
        currentLocation: "ملغاة",
        deletedReason: "إلغاء إداري بناءً على رغبة العميل",
      }),
    ],
    segments: [
      makeSegment(
        "s-01a",
        "i-01-1",
        "المستودع",
        3,
        "مستلم",
        "مستلم في المستودع بانتظار اكتمال القطعة الأخيرة",
      ),
      makeSegment(
        "s-01b",
        "i-01-4",
        "الجودة والتغليف",
        1,
        "بانتظار الفحص",
        "القطعة الرابعة تحت التغليف النهائي",
        "الإنتاج والإصلاح",
      ),
      makeSegment(
        "s-01c",
        "i-01-5",
        "ملغاة",
        1,
        "ملغاة",
        "إلغاء إداري بناءً على رغبة العميل",
        "الإدارة",
      ),
    ],
  },
];
