import type { MvpEmployee, MvpCustomer } from "./mvp-types";

export const seedEmployees: MvpEmployee[] = [
  {
    name: "محمد العتيبي",
    email: "admin@oriental.test",
    phone: "0501112200",
    requested: "admin",
    role: "admin",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  {
    name: "ريم خالد",
    email: "sales@oriental.test",
    phone: "0531927741",
    requested: "sales",
    role: "sales",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  {
    name: "خالد منصور",
    email: "approval@oriental.test",
    phone: "0502223344",
    requested: "approval",
    role: "approval",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  {
    name: "سالم الحربي",
    email: "cutting@oriental.test",
    phone: "0503334455",
    requested: "cutting",
    role: "cutting",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  {
    name: "أحمد عادل",
    email: "production@oriental.test",
    phone: "0554608812",
    requested: "production",
    role: "production",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  {
    name: "فهد ياسين",
    email: "special@oriental.test",
    phone: "0505556677",
    requested: "special",
    role: "special",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  {
    name: "منى سعيد",
    email: "quality@oriental.test",
    phone: "0506667788",
    requested: "quality",
    role: "quality",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  {
    name: "سارة محمد",
    email: "warehouse@oriental.test",
    phone: "0507778899",
    requested: "warehouse",
    role: "warehouse",
    status: "فعال",
    password: "Demo123!",
    registered: "٠١ سبتمبر ٢٠٢٦",
  },
  // Pending
  {
    name: "ياسر محمود",
    email: "yasser.work@gmail.com",
    phone: "0567092140",
    requested: "cutting",
    status: "بانتظار الموافقة",
    password: "Demo123!",
    registered: "١١ سبتمبر ٢٠٢٦",
  },
  // Rejected
  {
    name: "نورة حمد",
    email: "noura.hamad@gmail.com",
    phone: "0503351002",
    requested: "quality",
    status: "مرفوض",
    password: "Demo123!",
    registered: "١٠ سبتمبر ٢٠٢٦",
  },
  // Suspended
  {
    name: "طارق أمين",
    email: "tareq.ameen@gmail.com",
    phone: "0541179230",
    requested: "warehouse",
    role: "warehouse",
    status: "موقوف",
    password: "Demo123!",
    registered: "٠٥ سبتمبر ٢٠٢٦",
  },
];

export const seedCustomers: MvpCustomer[] = [
  {
    name: "أحمد عبدالرحمن",
    phone: "0503849217",
    address: "حي الروضة، جدة",
    email: "ahmad@example.com",
    notes: "عميل دائم للمعرض، يفضل المقاس ٤٢ والجلد الطبيعي",
  },
  {
    name: "متجر دار الخطوة",
    phone: "0557721034",
    address: "شارع التحلية، جدة",
    email: "daralkhotwa@gmail.com",
    notes: "مؤسسة تجارية شريكة، توريد دفعات شهرية",
  },
  {
    name: "يوسف الشريف",
    phone: "0531187042",
    address: "حي النزهة، مكة",
    email: "yousef@gmail.com",
    notes: "طلبات إصلاح متكررة لأحذية فاخرة",
  },
  {
    name: "ناصر العمري",
    phone: "0564908831",
    address: "حي الصفا، جدة",
    email: "nasser@gmail.com",
    notes: "عميل خاص",
  },
  {
    name: "بيت النخبة",
    phone: "0542281990",
    address: "شارع التحلية، جدة",
    email: "alnokhbar@gmail.com",
    notes: "معرض راقي للأحذية الشرقية",
  },
  {
    name: "خالد الزهراني",
    phone: "0506641280",
    address: "حي الصفا، جدة",
    email: "khaled.z@gmail.com",
    notes: "طلب جلد نعام خاص",
  },
  {
    name: "معرض المقاس",
    phone: "0555107613",
    address: "طريق المدينة، جدة",
    email: "almaqas@outlook.com",
    notes: "طلبات جملة مع كراتين فاخرة",
  },
  {
    name: "فارس القحطاني",
    phone: "0536001882",
    address: "حي الشاطئ، جدة",
    email: "fares.q@gmail.com",
    notes: "",
  },
  {
    name: "مازن فؤاد",
    phone: "0568322910",
    address: "حي النسيم، جدة",
    email: "mazen.f@gmail.com",
    notes: "طلب إصلاح كعب",
  },
  {
    name: "مؤسسة خطوة",
    phone: "0558871200",
    address: "حي الروضة، مكة",
    email: "khotwa.est@gmail.com",
    notes: "عميل تجاري مكتمل",
  },
];
