import type { MvpOrder } from "./mvp-types";
import { makePiece } from "./fixture-builders";
import { makeSegment } from "./mvp-selectors";

export const productionOrders: MvpOrder[] = [
  // 5. EXTERNAL-2026-0004 (Requirement 19: 4 pieces, 3 reached production, 1 has problem in approval)
  {
    id: "EXTERNAL-2026-0004",
    type: "EXTERNAL",
    customer: "متجر دار الخطوة",
    phone: "0557721034",
    address: "شارع التحلية، جدة",
    salesperson: "ليان سعد",
    created: "٠٦ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-06",
    delivery: "١٦ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-16",
    status: "قيد التصنيع",
    cancelled: 0,
    warehouse: 0,
    total: "1800",
    paid: "1000",
    balance: "800",
    items: [
      makePiece("i-04-1", 0, "OS-188", {
        size: "٤١",
        leatherBase: "جلد طبيعي أسود",
        decoration: "جلد بني محبب",
        decorationColor: "بني داكن",
        face: "وجه سادة كلاسيكي",
        sole: "R.D1/2 ربل مدعم",
        currentLocation: "في الإنتاج",
        deptStatus: "جاهزة للعمل",
        unitPrice: "450",
        rowTotal: "450",
      }),
      makePiece("i-04-2", 1, "OS-188", {
        size: "٤١",
        leatherBase: "جلد طبيعي أسود",
        decoration: "جلد بني محبب",
        decorationColor: "بني داكن",
        face: "وجه سادة كلاسيكي",
        sole: "R.D1/2 ربل مدعم",
        currentLocation: "في الإنتاج",
        deptStatus: "جاري العمل",
        responsibleWorker: "أحمد عادل",
        unitPrice: "450",
        rowTotal: "450",
      }),
      makePiece("i-04-3", 2, "OS-188", {
        size: "٤١",
        leatherBase: "جلد طبيعي أسود",
        decoration: "جلد بني محبب",
        decorationColor: "بني داكن",
        face: "وجه سادة كلاسيكي",
        sole: "R.D1/2 ربل مدعم",
        currentLocation: "في الإنتاج",
        deptStatus: "جاهزة للعمل",
        unitPrice: "450",
        rowTotal: "450",
      }),
      makePiece("i-04-4", 3, "OS-188", {
        size: "٤١",
        leatherBase: "جلد طبيعي أسود",
        decoration: "جلد بني محبب",
        decorationColor: "بني داكن",
        face: "وجه سادة كلاسيكي",
        sole: "R.D1/2 ربل مدعم",
        currentLocation: "لدى الاعتماد بسبب مشكلة",
        deptStatus: "بها مشكلة",
        unitPrice: "450",
        rowTotal: "450",
        problem: {
          reportedByDept: "القص",
          reportedByWorker: "سالم الحربي",
          reason: "عيب في تشطيب جلد الأساس",
          notes:
            "الحاجة لتأكيد موافقة العميل على استبدال جلد الأساس أو اعتماد جلد بديل",
          reportedAt: "٠٨ سبتمبر ٢٠٢٦ · ١١:٣٠",
          status: "pending",
        },
      }),
    ],
    segments: [
      makeSegment(
        "s-04a",
        "i-04-1",
        "الإنتاج والإصلاح",
        1,
        "بانتظار بدء العمل",
        "محولة من القص إلى الإنتاج",
        "القص",
      ),
      makeSegment(
        "s-04b",
        "i-04-2",
        "الإنتاج والإصلاح",
        1,
        "قيد التنفيذ",
        "تركيب الوجه وتثبيت الأرضية",
        "القص",
        undefined,
        "أحمد عادل",
      ),
      makeSegment(
        "s-04c",
        "i-04-3",
        "الإنتاج والإصلاح",
        1,
        "بانتظار بدء العمل",
        "محولة من القص إلى الإنتاج",
        "القص",
      ),
      makeSegment(
        "s-04d",
        "i-04-4",
        "القص",
        1,
        "بها مشكلة",
        "لدى الاعتماد بسبب مشكلة",
        "القص",
      ),
    ],
  },
  // 5b. Partially Completed Item: 3 in Warehouse, 3 in Production WIP
  {
    id: "EXTERNAL-2026-0005",
    type: "EXTERNAL",
    customer: "مؤسسة خطوة الأناقة",
    phone: "0554198231",
    address: "حي الروضة، جدة",
    salesperson: "ليان سعد",
    created: "٠٥ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-05",
    delivery: "١٧ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-17",
    status: "قيد التصنيع",
    cancelled: 0,
    warehouse: 3,
    items: [
      makePiece("i-05x-1", 0, "OS-199", {
        size: "٤٣",
        leatherBase: "جلد طبيعي عسلي فاخر",
        currentLocation: "في المستودع",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-05x-2", 1, "OS-199", {
        size: "٤٣",
        leatherBase: "جلد طبيعي عسلي فاخر",
        currentLocation: "في المستودع",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-05x-3", 2, "OS-199", {
        size: "٤٣",
        leatherBase: "جلد طبيعي عسلي فاخر",
        currentLocation: "في المستودع",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-05x-4", 3, "OS-199", {
        size: "٤٣",
        leatherBase: "جلد طبيعي عسلي فاخر",
        currentLocation: "في الإنتاج",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-05x-5", 4, "OS-199", {
        size: "٤٣",
        leatherBase: "جلد طبيعي عسلي فاخر",
        currentLocation: "في الإنتاج",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-05x-6", 5, "OS-199", {
        size: "٤٣",
        leatherBase: "جلد طبيعي عسلي فاخر",
        currentLocation: "في الإنتاج",
        deptStatus: "جاهزة للعمل",
      }),
    ],
    segments: [
      makeSegment(
        "s-05w",
        "i-05x-1",
        "المستودع",
        3,
        "بانتظار الاستلام",
        "الدفعة الأولى اكتملت ووصلت المستودع وبانتظار فرز وتأكيد الكراتين بالرف W-12",
        "الجودة والتغليف",
        undefined,
        "سارة محمد",
        "٠٩ سبتمبر ٢٠٢٦ · ١٤:٠٠",
      ),
      makeSegment(
        "s-05p",
        "i-05x-4",
        "الإنتاج والإصلاح",
        3,
        "بانتظار الاستلام",
        "الدفعة المتبقية محولة من القص بانتظار استلام وبدء التجميع والتركيب",
        "القص",
        undefined,
        "أحمد عادل",
        "٠٨ سبتمبر ٢٠٢٦ · ٠٨:٣٠",
      ),
    ],
  },
  // 6. Quality Rejection returned to Cutting
  {
    id: "SHOP-2026-0007",
    type: "SHOP",
    customer: "ناصر العمري",
    phone: "0564908831",
    address: "حي الصفا، جدة",
    salesperson: "ليان سعد",
    created: "٠١ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-01",
    delivery: "٠٩ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-09",
    status: "قيد التصنيع",
    cancelled: 0,
    warehouse: 0,
    items: [
      makePiece("i-07-1", 0, "OS-207", {
        leatherBase: "جلد هافان",
        currentLocation: "في القص",
        deptStatus: "مرتجعة للتصحيح",
        rejection: {
          responsibleDept: "القص",
          reason: "انحراف في حافة القص الجانبية",
          notes: "انحراف بمقدار ٢ مم · إعادة القص وضبط المقاس",
          cycle: 1,
          returnedAt: "٠٨ سبتمبر · ١١:٢٠",
        },
      }),
      makePiece("i-07-2", 1, "OS-207", {
        leatherBase: "جلد هافان",
        currentLocation: "في الجودة",
        deptStatus: "جاهزة للفحص",
      }),
      makePiece("i-07-3", 2, "OS-207", {
        leatherBase: "جلد هافان",
        currentLocation: "في الجودة",
        deptStatus: "جاهزة للفحص",
      }),
      makePiece("i-07-4", 3, "OS-207", {
        leatherBase: "جلد هافان",
        currentLocation: "في الجودة",
        deptStatus: "جاري الفحص",
        responsibleWorker: "منى سعيد",
      }),
    ],
    segments: [
      makeSegment(
        "s-07a",
        "i-07-1",
        "القص",
        1,
        "معادة من الجودة",
        "انحراف في حافة القص الجانبية بمقدار ٢ مم · إعادة القص وضبط المقاس",
        "الجودة والتغليف",
        1,
      ),
      makeSegment(
        "s-07b",
        "i-07-2",
        "الجودة والتغليف",
        2,
        "بانتظار الاستلام",
        "بانتظار استلام وبدء فحص باقي الكمية",
        "الإنتاج والإصلاح",
      ),
      makeSegment(
        "s-07c",
        "i-07-4",
        "الجودة والتغليف",
        1,
        "قيد التنفيذ",
        "تحت الفحص والمطابقة الدقيقة لقياس النعل",
        "الإنتاج والإصلاح",
        undefined,
        "منى سعيد",
        "٠٨ سبتمبر ٢٠٢٦ · ١٢:٠٠",
      ),
    ],
    corrections: [
      {
        id: "qc-07",
        itemId: "i-07-1",
        segmentId: "s-07a",
        quantity: 1,
        responsible: "القص",
        reason: "انحراف في حافة القص الجانبية",
        instructions: "إعادة ضبط زاوية القص وتوحيد الحواف وفق العينة",
        cycle: 1,
        date: "٠٨ سبتمبر · ١١:٢٠",
        actor: "منى سعيد",
        resolved: false,
      },
    ],
  },
];
