import type { MvpOrder } from "./mvp-types";
import { makePiece, makeSegment } from "./fixture-builders";

export const intakeOrders: MvpOrder[] = [
  // 1. Draft Order
  {
    id: "SHOP-2026-0009",
    type: "SHOP",
    customer: "سعد الدوسري",
    phone: "0509981044",
    address: "حي السلامة، جدة",
    salesperson: "ريم خالد",
    created: "١١ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-11",
    delivery: "٢٨ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-28",
    status: "مسودة",
    cancelled: 0,
    warehouse: 0,
    items: [
      makePiece("i-09-1", 0, "OS-231", { size: "٤٣", decoration: "جلد جملي" }),
      makePiece("i-09-2", 1, "OS-231", { size: "٤٣", decoration: "جلد جملي" }),
      makePiece("i-09-3", 2, "OS-231", { size: "٤٣", decoration: "جلد جملي" }),
    ],
    segments: [],
    generalNotes: "مسودة مبدئية بانتظار تأكيد العميل للمقاس",
  },
  // 2. Returned Sales Order
  {
    id: "SHOP-2026-0011",
    type: "SHOP",
    customer: "أحمد عبدالرحمن",
    phone: "0503849217",
    address: "حي الروضة، جدة",
    salesperson: "ريم خالد",
    created: "١١ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-11",
    delivery: "٢٦ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-26",
    status: "معاد للتعديل",
    cancelled: 0,
    warehouse: 0,
    returnReason:
      "لون التطعيم غير محدد في السطر الثاني، يرجى التحديد الدقيق قبل الاعتماد",
    reviewer: "خالد منصور",
    returnedAt: "١١ سبتمبر ٢٠٢٦ · ١٤:١٥",
    items: [
      makePiece("i-11a", 0, "OS-214", { decorationColor: "بني محروق" }),
      makePiece("i-11b", 1, "OS-215", { decorationColor: "" }),
    ],
    segments: [],
  },
  // 3. Awaiting Approval
  {
    id: "EXTERNAL-2026-0008",
    type: "EXTERNAL",
    customer: "بيت النخبة",
    phone: "0542281990",
    address: "شارع التحلية، جدة",
    salesperson: "ريم خالد",
    created: "١٠ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-10",
    delivery: "٢٥ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-25",
    status: "بانتظار الاعتماد",
    cancelled: 0,
    warehouse: 0,
    items: [
      makePiece("i-08a-1", 0, "OS-188", {
        size: "٤٢",
        sole: "R.D1/2 ربل مدعم",
      }),
      makePiece("i-08a-2", 1, "OS-188", {
        size: "٤٢",
        sole: "R.D1/2 ربل مدعم",
      }),
      makePiece("i-08b-1", 2, "OS-190", { size: "٤٤", sole: "R.O ربل عادي" }),
      makePiece("i-08b-2", 3, "OS-190", { size: "٤٤", sole: "R.O ربل عادي" }),
    ],
    segments: [],
    generalNotes: "طلب لفرع التحلية الجديد، الالتزام بالموعد",
  },
  // 4. Approved Showroom Order entering Cutting
  {
    id: "SHOP-2026-0010",
    type: "SHOP",
    customer: "خالد الزهراني",
    phone: "0506641280",
    address: "حي الصفا، جدة",
    salesperson: "ريم خالد",
    created: "١٠ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-10",
    delivery: "٢٤ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-24",
    status: "قيد التصنيع",
    cancelled: 0,
    warehouse: 0,
    items: [
      makePiece("i-10-1", 0, "OS-220", {
        leatherBase: "جلد نعام طبيعي",
        decoration: "سادة بدون تطعيم",
        currentLocation: "في القص",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-10-2", 1, "OS-220", {
        leatherBase: "جلد نعام طبيعي",
        decoration: "سادة بدون تطعيم",
        currentLocation: "في القص",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-10-3", 2, "OS-220", {
        leatherBase: "جلد نعام طبيعي",
        decoration: "سادة بدون تطعيم",
        currentLocation: "في القص",
        deptStatus: "جاهزة للعمل",
      }),
    ],
    segments: [
      makeSegment(
        "s-10",
        "i-10-1",
        "القص",
        3,
        "بانتظار الاستلام",
        "قص دقيق لجلد النعام",
        "الاعتماد",
      ),
    ],
  },
  // 4b. Order with Two Segments inside the SAME Department (Cutting)
  {
    id: "SHOP-2026-0012",
    type: "SHOP",
    customer: "تركي الشمري",
    phone: "0548819200",
    address: "حي المحمدية، جدة",
    salesperson: "ريم خالد",
    created: "١٠ سبتمبر ٢٠٢٦",
    createdIso: "2026-09-10",
    delivery: "٢٥ سبتمبر ٢٠٢٦",
    deliveryIso: "2026-09-25",
    status: "قيد التصنيع",
    cancelled: 0,
    warehouse: 0,
    items: [
      makePiece("i-12-1", 0, "OS-210", {
        size: "٤٤",
        leatherBase: "جلد نعام طبيعي كحلي",
        currentLocation: "في القص",
        deptStatus: "جاري العمل",
        responsibleWorker: "سالم الحربي",
      }),
      makePiece("i-12-2", 1, "OS-210", {
        size: "٤٤",
        leatherBase: "جلد نعام طبيعي كحلي",
        currentLocation: "في القص",
        deptStatus: "جاري العمل",
        responsibleWorker: "سالم الحربي",
      }),
      makePiece("i-12-3", 2, "OS-210", {
        size: "٤٤",
        leatherBase: "جلد نعام طبيعي كحلي",
        currentLocation: "في القص",
        deptStatus: "جاهزة للعمل",
      }),
      makePiece("i-12-4", 3, "OS-210", {
        size: "٤٤",
        leatherBase: "جلد نعام طبيعي كحلي",
        currentLocation: "في القص",
        deptStatus: "جاهزة للعمل",
      }),
    ],
    segments: [
      makeSegment(
        "s-12a",
        "i-12-1",
        "القص",
        2,
        "قيد التنفيذ",
        "الدفعة الأولى: قص الوجه والبطانة للمقاس ٤٤",
        "الاعتماد",
        undefined,
        "سالم الحربي",
        "١٠ سبتمبر ٢٠٢٦ · ٠٩:٣٠",
      ),
      makeSegment(
        "s-12b",
        "i-12-3",
        "القص",
        2,
        "بانتظار الاستلام",
        "الدفعة الثانية: قص الأطراف والتفاصيل السفلية",
        "الاعتماد",
        undefined,
        undefined,
        "١٠ سبتمبر ٢٠٢٦ · ٠٩:٣٠",
      ),
    ],
  },
];
